name: Run .NET Tests with Mongo and Azurite

on:
  push:
    branches:
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002

    env:
      MONGO__CONNECTIONSTRING: mongodb://localhost:27017
      AZURITE__BLOB_CONNECTIONSTRING: UseDevelopmentStorage=true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test OpenFlowWebServer.Domain.Tests.Unit.csproj --no-build --configuration Release

      - name: Run Integration Tests
        run: dotnet test OpenFlowWebServer.Repository.Tests.Integration.csproj --no-build --configuration Release
